# Generated by Django 4.2.4 on 2023-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('is_update', models.BooleanField(blank=True, null=True)),
                ('is_actual', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
