# Generated by Django 4.2.4 on 2023-08-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hac_app', '0003_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='type_id',
            new_name='type',
        ),
    ]
