# Generated by Django 4.2.4 on 2023-08-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hac_app', '0010_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('house', models.TextField(blank=True, null=True)),
                ('corpus', models.TextField(blank=True, null=True)),
                ('liter', models.TextField(blank=True, null=True)),
                ('villa', models.TextField(blank=True, null=True)),
                ('parcel', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('is_updated', models.BooleanField(blank=True, null=True)),
                ('is_actual', models.BooleanField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('municipality_id', models.IntegerField(blank=True, null=True)),
                ('short_address', models.TextField(blank=True, null=True)),
                ('post_prefix', models.TextField(blank=True, null=True)),
                ('build_number', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hac_app.district')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hac_app.prefix')),
            ],
        ),
    ]
